# Generated by Django 6.0.5 on 2026-05-07 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
